apiVersion: v1
kind: Service
metadata:
  name: hello-eks-svc
  labels:
    version: v1
    app: hello-eks
spec:
  selector:
    app: hello-eks
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
